### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by it4e** [ImFalling/Spirograph-JS#1]
I like what you have done! 

However, I am having a hard time trying to utilize the library since there isn't really an obvious explicit interface abstracting the different functionality. How about encapsulating the functionality in some kind of class or object as well as documenting how to use it? Some kind of API reference?

**Comment by ImFalling** [comment]
Maybe you could just learn JavaScript, noob. But just for you, I'll make an effort to simplify it for your feeble assembler mind.

**Comment by ImFalling** [comment]
I didn't want to do any major changes, so I added a proper readme, and a simple demo in the script.js file to understand the basics. Hopefully it's enough to help you understand.
